---
title: "FNA 1117"
author: "JW Yi"
date: "Monday, November 17, 2014"
output: html_document
---

```{r, echo=FALSE, results='hide'}
fnadata <- readRDS("D://Work/FNA/FNA from 2007.rds")
library(RColorBrewer); library(ggplot2)
```

# Univariable Logistic Regression Result, Odds ratio and 95% CI

```{r, echo=FALSE}
logit1 <- glm(FNA_Cat ~ Sex, family="binomial", data=fnadata)
a <- round(summary(logit1)$coef, 5)
logit2 <- glm(FNA_Cat ~ Age_Cat, family="binomial", data=fnadata)
b <- round(summary(logit2)$coef, 5)
logit3 <- glm(FNA_Cat ~ USG, family="binomial", data=fnadata)
c <- round(summary(logit3)$coef, 5)
fnadata$Size_Cat <- factor(fnadata$Size_Cat, levels=c("Above 3cm", "Below 3cm"))
logit4 <- glm(FNA_Cat ~ Size_Cat, family="binomial", data=fnadata)
d <- round(summary(logit4)$coef, 5)
aci <- cbind(OR = exp(logit1$coef), exp(confint(logit1)))
bci <- cbind(OR = exp(logit2$coef), exp(confint(logit2)))
cci <- cbind(OR = exp(logit3$coef), exp(confint(logit3)))
dci <- cbind(OR = exp(logit4$coef), exp(confint(logit4)))

result1 <- rbind(a,b,c,d)
result2 <- rbind(aci, bci, cci, dci)

result.univariable <- cbind(result1, result2)
result.univariable
```

# Multivariable Logistic Regression Result, Odds ratio and 95% CI

```{r, echo=FALSE}
logit.all <- glm(FNA_Cat ~ Sex + Age_Cat + USG + Size_Cat, family="binomial", data=fnadata)

result3 <- round(summary(logit.all)$coef, 5)
result4 <- cbind(OR = exp(logit.all$coef), exp(confint(logit.all)))
result.multivariable <- cbind(result3, result4)
result.multivariable
```

# Barplot Style 1
```{r, echo=FALSE}
col <- brewer.pal(5, "Set1")
tx <- table(fnadata$FNA_Cat, fnadata$Size_Range)
b <- barplot(tx, col=col[2:1], ylim=c(0, 120), 
             xlab="Tumor Size", 
             ylab="n", xaxt="n")
axis(1, at=c(0.7,1.9,3.1,4.3), lab=c("¡Â 1.0cm","1.1-2.0cm", "2.1-3.0cm",">3.0cm"), las=1, cex=0.7)
text(0.7, 22, "44 (42.3%)")
text(0.7, 71, "60 (57.7%)")
text(1.9, 21, "42 (56.0%)")
text(1.9, 59, "33 (44.0%)")
text(3.1, 9, "17 (60.7%)")
text(3.1, 32, "11 (39.3%)")
text(4.3, 8, "15 (83.3%)")
text(4.3, 22, "3 (16.7%)")
legend(3.8, 115, legend = c("Group A", "Group B"), 
       fill = col[1:2], bty="n")
box()
```

# Barplot Style 2
```{r, echo=FALSE}
fnadata$FNA_Cat <- factor(fnadata$FNA_Cat, levels=c("Benign","Malignant"), labels=c("Negative-FNA","Positive-FNA"))
fnadata$Size_Range <- factor(fnadata$Size_Range, levels=c("0-1","1-2","2-3","3>"), labels=c("¡Â1.0cm","1.1-2.0cm","2.1-3.0cm",">3.0cm"))

g <- ggplot(fnadata, aes(x=Size_Range, fill=FNA_Cat)) +
        geom_bar(width=0.5) +
        guides(fill=guide_legend(reverse=TRUE)) +
        scale_fill_manual(values=brewer.pal(4, "Set2")[c(1,2)],
                          guide=guide_legend(reverse=TRUE),
                          labels=c("Group A","Group B")) +
        labs(title="Diagnostic Accuracy of FNA\nIn FVPTC", 
             x="Tumor Size", y="n", fill="FNA Category") +
        geom_text(aes(1,22,label="44\n(42.3%)"), size=4, col="grey40") +
        geom_text(aes(1,74,label="60\n(57.7%)"), size=4, col="grey40") +
        geom_text(aes(2,21,label="42\n(56.0%)"), size=4, col="grey40") +
        geom_text(aes(2,58.5,label="33\n(44.0%)"), size=4, col="grey40") +
        geom_text(aes(3,8.5,label="17\n(60.7%)"), size=4, col="grey40") +
        geom_text(aes(3,22.5,label="11\n(39.3%)"), size=4, col="grey40") +
        geom_text(aes(4,7.5,label="15\n(83.3%)"), size=4, col="grey40") +
        geom_text(aes(4,23,label="3\n(16.7%)"), size=4, col="grey40")

g
```